stages:
  preprocess_dataset:
    wdir: .
    cmd: PYTHONPATH=. python3 experiments/scripts/preprocess_dataset.py
    params:
      - preprocess_dataset.smiles2grap
    deps:
      - experiments/scripts/preprocess_dataset.py
    outs:
      - data/dataset/

  train_supervised:
    wdir: .
    foreach:
      - diffpool
    cmd: PYTHONPATH=. python3 experiments/scripts/train_supervised.py --model ${item} --config-path experiments/configs/${item}.yaml --checkpoint_dir data/supervised/${item}/checkpoints --save-test-dir data/supervised/${item}/submssion --metrics-path data/metrics/supervised/${item}.json --log-dir data/supervised/${item}/logs
    params:
      - experiments/configs/${item}.yaml
    deps:
      - data/dataset/
    metrics:
      - data/metrics/supervised/${item}.json:
          cache: false
    outs:
      - data/supervised/${item}/
