stages:
  preprocess_dataset:
    wdir: .
    cmd: PYTHONPATH=. python3 experiments/scripts/preprocess_dataset.py
    params:
      - preprocess_dataset.smiles2grap
    deps:
      - experiments/scripts/preprocess_dataset.py
    outs:
      - data/dataset/