stages:
  preprocess_dataset:
    foreach: ${datasets} # From params.yaml
    do:
      wdir: .
      cmd: PYTHONPATH=. python3 experiments/scripts/preprocess_dataset.py --dataset ${item.name}
      deps:
        - params.yaml
        - experiments/scripts/preprocess_dataset.py
      outs:
        - ${item.output_path}

  train_supervised:
    foreach:
      - gin-virtual
      - gin-virtual-diffpool
    do:
      wdir: .
      cmd: PYTHONPATH=. python3 experiments/scripts/train_supervised.py --model-name ${item} --config-path experiments/configs/${item}.yaml --checkpoint-dir data/supervised/${item}/checkpoints --save-test-dir data/supervised/${item}/submssion --metrics-path data/metrics/supervised/${item}/ --log-dir data/supervised/${item}/logs
      params:
        - experiments/configs/${item}.yaml:
            - args
            - learning_args
            - step_lr
            - data_loader_args
            - dataset
            - reg
      deps:
        - data/dataset/pcqm4m_kddcup2021/processed/
      metrics:
        - data/metrics/supervised/${item}/all.json:
            cache: false
      outs:
        - data/supervised/${item}/


  make_predictions:
    cmd: PYTHONPATH=. python3 experiments/scripts/make_predictions.py --config-path experiments/configs/make_predictions.yaml
    deps:
      - experiments/configs/make_predictions.yaml
      - experiments/scripts/make_predictions.py
    outs:
      - data/predictions/predictions.pkl

  get_representations:
    cmd: PYTHONPATH=. python3 experiments/scripts/get_representations.py --config-path experiments/configs/make_predictions.yaml
    deps:
      - experiments/configs/make_predictions.yaml
      - experiments/scripts/make_predictions.py
      - data/supervised
    outs:
      - data/predictions/representations.pkl
      - data/predictions/error_group_split_idx.pkl
      - data/predictions/error_group_split_idx_groups_mapping.pkl
