preprocess_dataset:
  smiles2graph:
    cls: src.smiles.Smiles2GraphOGBConverter
    args: {}

# Unsupervised models
gae:
  # graph_pooling: "sum"
  # drop_ratio: 0.7
  num_layers: 3
  emb_dim: 128
  batch_size: 512
  epochs: 5

gunet:
  depth: 3
  emb_dim: 128
  batch_size: 512
  epochs: 5